# Generated by Django 5.0.1 on 2025-06-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_slug_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(choices=[('local', 'Local'), ('imported', 'Importé'), ('organic', 'Bio'), ('conventional', 'Conventionnel'), ('fair_trade', 'Commerce équitable')], default='local', max_length=20),
        ),
    ]
